### ISSUE TITLE
Consider small conformance test SDK

### ISSUE THREAD

**Issue by rylev** [fermyon/conformance-tests#8]
The components in the `components` directory deliberately do not use a Spin SDK in order to make it extremely clear what the components are doing at the component boundary. While the SDKs are meant to make the developers life easier at the expense of being (at times) a bit opaque, the conformance tests should make the opposite trade-off.

However, there are a few things that happen often in conformance components that are not central to the test and which can be tedious and error prone which might benefit from being centralized. For example, writing the responses from an http-trigger happens in nearly every test. This requires using the somewhat finicky `wasi:http/incoming-handler`'s interface along with the various streaming types which is not trivial. 

Should we move these to a central place and use a shared library for abstracting some of these common functions? How do we decide what should go into the SDK and what should not?

**Comment by lann** [comment]
I could dust off https://github.com/lann/wasi-hyperium ...

**Comment by rylev** [comment]
While that's a very cool project that should definitely exist, I'm not sure it's the right balance here of being very transparent as to which wasi calls are actually happening while still eliminating some copy/pasting. What I had in mind was much simpler: consolidate some functionality together in the form of simple functions while still being extremely transparent as to what is happening at the component boundary.

**Comment by lann** [comment]
Probably for the best. I don't _really_ have time to do it anyway... :sweat_smile:
